# Configuración del servidor
server.port=8080

# Configuración de Spring Boot
spring.application.name=facial-recognition-api

# Configuración de tamaño máximo de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configuración de logging
logging.level.com.admcontenidos.facialrecognition=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
